//KomalBhamare
//24-01-2023
#include<iostream.h>
#include<conio.h>
void main()
{
	int arr=[20],i,n;
	clrscr();
	cout<<"Enter array element:-";
	for(i=0;i<5;i++)
	{
		cout<<arr[i];
	}
	cout<<"\nEnter number to insert:-";
	cin>>n;
	for(i=0;i<5;i++)
	{
		cout<<arr[i]<<"  ";
	}
	cout<<endl;
getch();
}


output:-
Enter array element:-1 2 3 1 4                                                  
                                                                                
Enter number to insert:-5                                                       
                                                                                
 New array is:-1 2 3 1 4 5     